name: Docker CI/CD

on:
  push:
    branches:
      - main  #Lo haremos en la rama que estemos trabajando en cad amomento.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t your-image-name:latest .
      
    - name: Run Tests
      run: |
        docker run --rm your-image-name:latest your-test-command

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Define este secreto en tu repositorio
        password: ${{ secrets.DOCKER_PASSWORD }}  # Define este secreto en tu repositorio

    - name: Push Docker Image
      run: |
        docker push your-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Esto asegura que el trabajo de despliegue espere a que se complete el trabajo de construcción

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Server
      run: |
        ssh user@your-server-ip "docker pull your-image-name:latest && docker run -d your-image-name:latest"
