name: Docker CI/CD

on:
  push:
    branches:
      - main  # Lo haremos en la rama que estemos trabajando en cada momento.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Check if Dockerfile Exists
      id: check_dockerfile
      run: |
        if [ ! -f Dockerfile ]; then
          echo "Dockerfile not found, skipping build."
          exit 0
        fi

    - name: Build Docker Image
      if: steps.check_dockerfile.outcome == 'success'
      run: |
        docker build -t your-image-name:latest .
      
    - name: Check if Docker Image Exists
      id: check_image
      run: |
        if ! docker images -q your-image-name:latest; then
          echo "No Docker image found. No image was built."
          exit 0
        fi

    - name: Run Tests
      if: steps.check_image.outcome == 'success'
      run: |
        docker run --rm your-image-name:latest your-test-command

    - name: Login to Docker Hub
      if: steps.check_image.outcome == 'success'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Define este secreto en tu repositorio
        password: ${{ secrets.DOCKER_PASSWORD }}  # Define este secreto en tu repositorio

    - name: Push Docker Image
      if: steps.check_image.outcome == 'success'
      run: |
        docker push your-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Esto asegura que el trabajo de despliegue espere a que se complete el trabajo de construcción

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Server
      if: success()
      run: |
        ssh user@your-server-ip "docker pull your-image-name:latest && docker run -d your-image-name:latest"
